# Generated by Django 2.0.5 on 2018-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_status',
            fields=[
                ('site', models.TextField(primary_key=True, serialize=False)),
                ('source_url', models.TextField()),
                ('broken_url', models.TextField()),
            ],
            options={
                'db_table': 'url_status',
            },
        ),
        migrations.AlterUniqueTogether(
            name='url_status',
            unique_together={('site', 'source_url', 'broken_url')},
        ),
    ]
