# Generated by Django 2.0.5 on 2018-05-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brokenlinks',
            new_name='Brokenlink',
        ),
    ]
