# Generated by Django 2.0.5 on 2018-05-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenlink',
            name='temp_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapesites.Urllist'),
        ),
    ]
