# Generated by Django 2.0.5 on 2018-05-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urllist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('team', models.TextField()),
            ],
        ),
    ]
