# Generated by Django 2.0.5 on 2018-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0002_brokenlink_temp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='slack_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
