# Generated by Django 2.0.5 on 2018-05-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0002_urllist'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
