# Generated by Django 2.0.5 on 2018-06-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0003_urllist_slack_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urllist',
            name='slack_url',
        ),
    ]
