# Generated by Django 2.0.5 on 2018-05-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0004_auto_20180523_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllist',
            name='team',
            field=models.CharField(max_length=60),
        ),
    ]
