# Generated by Django 2.2.6 on 2019-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0005_auto_20191030_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenlink',
            name='updated_at',
        ),
    ]
