# Generated by Django 2.0.5 on 2018-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0007_auto_20180525_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='slack_sent',
            field=models.BooleanField(default=False),
        ),
    ]
