# Generated by Django 2.0.5 on 2018-05-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0008_urllist_slack_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='bad_link',
            field=models.BooleanField(default=False),
        ),
    ]
