# Generated by Django 2.0.5 on 2018-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0009_urllist_bad_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetime',
            name='previous_check_state',
            field=models.BooleanField(default=True),
        ),
    ]
