# Generated by Django 2.0.5 on 2018-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapesites', '0010_responsetime_previous_check_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetime',
            name='response_time',
            field=models.FloatField(default=0.0),
        ),
    ]
